server:
  port: 8090
security:
  ignored: /css/**,/js/**,/images/**,/webjars/**,/**/favicon.ico,/**/*.css,/**/*.js,/**/*.gif,/**/*.jpg,/**/*.bmp,/**/*.png,/**/*.ico
  oauth2:
    client:
      client-id: wmp
      client-secret: 5f4dcc3b5aa765d61d8327deb882cf99
      access-token-uri: http://192.168.0.88:19000/sso/oauth/token
      user-authorization-uri: http://192.168.0.88:19000/sso/oauth/authorize
      resource-ids: oauth2-resource
      logout-uri: "http://192.168.0.88:19000/sso/logout"
    resource:
      user-info-uri: http://192.168.0.88:19000/sso/resource/me
      #资源获取地址
      resources-uri: http://192.168.0.88:19000/sso/resource/get_all_resources
      #资源缓存时间，单位：秒
      resources-cachetime: 10
logging:
  level:
    org.springframework.security: WARN
    org.springframework.web: WARN
eureka:
  instance:
    preferIpAddress: true
  client:
    service-url:
      defaultZone: http://192.168.0.88:18001/eureka
spring:
  application:
    name: wmp
  datasource:
    url: jdbc:mysql://192.168.0.88:3306/WMP_DB?characterEncoding=utf8
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
# Specify the DBMS
  jpa:
   database: MYSQL
# Show or not log for each sql query
   show-sql: true
# Hibernate ddl auto (create, create-drop, update)
   hibernate:
      ddl-auto: update
      name-strategy: org.hibernate.cfg.improvedNamingStrategy
# Naming strategy
# stripped before adding them to the entity manager)
   properties:
     hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        cache:
          use_second_level_cache: false
          use_query_cache: false