server:
  port: 8090
security:
  oauth2:
    client:
      client-id: acmex
      client-secret: acmesecretx
      access-token-uri: http://192.168.0.95:19000/oauth/token
      user-authorization-uri: http://192.168.0.95:19000/oauth/authorize
    resource:
      user-info-uri: http://192.168.0.95:19000/resource/me
      #资源获取地址
      resources-uri: http://192.168.0.95:19000/resource/get_all_resources
      #资源缓存时间，单位：秒
      resources-cachetime: 10

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
eureka:
  client:
    service-url:
      defaultZone: http://192.168.0.95:18001/eureka
spring:
  datasource:
    url: jdbc:mysql://192.168.0.95:3306/WMP_HRM?characterEncoding=utf8
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
# Specify the DBMS
  jpa:
   database: MYSQL
# Show or not log for each sql query
   show-sql: true
# Hibernate ddl auto (create, create-drop, update)
   hibernate:
      ddl-auto: update
      name-strategy: org.hibernate.cfg.improvedNamingStrategy
# Naming strategy
# stripped before adding them to the entity manager)
   properties:
     hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        cache:
          use_second_level_cache: false
          use_query_cache: false
